apiVersion: apps/v1
kind: Deployment
metadata:
  name: yatri-bookings
  namespace: yatri-secure
spec:
  replicas: 2
  selector:
    matchLabels: { app: yatri-bookings }
  template:
    metadata:
      labels: { app: yatri-bookings }
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532              # distroless 'nonroot'
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: api
          image: ghcr.io/praneethb7/devops_assignment/yatri-bookings:latest
          ports:
            - containerPort: 8000
          env:
            - name: BOOKING_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-signing
                  key: BOOKING_SIGNING_KEY
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests: { cpu: 50m, memory: 64Mi }
            limits:   { cpu: 300m, memory: 192Mi }
          readinessProbe:
            httpGet: { path: /ready, port: 8000 }
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /health, port: 8000 }
            periodSeconds: 10
