# Asks the cloud provider for an external IP. Builds on NodePort, which builds on ClusterIP.
apiVersion: v1
kind: Service
metadata:
  name: web-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
